### ISSUE TITLE
Missing amd64 in arch_map causes runtime error in v0.0.2 on PyPI

### ISSUE THREAD

**Issue by Starsbon** [xuri/excelize-py#5]
Hi,
In the v0.0.2 version of excelize-py available on PyPI, the arch_map in the excelize.py file is missing support for the amd64 architecture. This causes the error:
This platform or architecture is not supported.
I noticed that this issue has been fixed in the newer version. Could you please let me know when the updated version will be synced to PyPI?

Thank you!

**Comment by xuri** [comment]
Thanks for your issue. The amd64 already added by commit [`e3a92ba`](https://github.com/xuri/excelize-py/commit/e3a92baf6ec9d7f4a7c2f3c53bee7b7497fb5a5e), this project still working in progress, will be bump new release after functions is implemented. Contribution are welcome.
